<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-ITJ9AKB" failures="6" tests="21" name="Test1" time="84.752" errors="0" timestamp="2025-07-09T22:57:21 IST">
  <testcase classname="TestScripts.googlepagetest_new" name="display1" time="0.003"/>
  <testcase classname="TestScripts.googlepagetest_new" name="display2" time="0.013">
    <skipped/>
  </testcase> <!-- display2 -->
  <testcase classname="TestScripts.googlepagetest_new" name="display2" time="0.004">
    <skipped/>
  </testcase> <!-- display2 -->
  <testcase classname="TestScripts.googlepagetest_new" name="display2" time="0.015">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at TestScripts.googlepagetest_new.display2(googlepagetest_new.java:31)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- display2 -->
  <testcase classname="TestScripts.googlepagetest_new" name="openurl" time="4.946"/>
  <testcase classname="TestScripts.googlepageTest" name="display1" time="0.002">
    <skipped/>
  </testcase> <!-- display1 -->
  <testcase classname="TestScripts.googlepageTest" name="display1" time="0.041">
    <skipped/>
  </testcase> <!-- display1 -->
  <testcase classname="TestScripts.googlepageTest" name="display1" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at TestScripts.googlepageTest.display1(googlepageTest.java:29)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- display1 -->
  <testcase classname="TestScripts.googlepageTest" name="display4" time="0.005">
    <skipped/>
  </testcase> <!-- display4 -->
  <testcase classname="TestScripts.googlepageTest" name="display4" time="0.003">
    <skipped/>
  </testcase> <!-- display4 -->
  <testcase classname="TestScripts.googlepageTest" name="display4" time="0.016">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at TestScripts.googlepageTest.display4(googlepageTest.java:36)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- display4 -->
  <testcase classname="TestScripts.googlepageTest" name="display5" time="0.007">
    <skipped/>
  </testcase> <!-- display5 -->
  <testcase classname="TestScripts.googlepageTest" name="display5" time="0.002">
    <skipped/>
  </testcase> <!-- display5 -->
  <testcase classname="TestScripts.googlepageTest" name="display5" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at TestScripts.googlepageTest.display5(googlepageTest.java:43)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- display5 -->
  <testcase classname="TestScripts.googlepageTest" name="display6" time="0.001">
    <skipped/>
  </testcase> <!-- display6 -->
  <testcase classname="TestScripts.googlepageTest" name="display6" time="0.002">
    <skipped/>
  </testcase> <!-- display6 -->
  <testcase classname="TestScripts.googlepageTest" name="display6" time="0.005">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at TestScripts.googlepageTest.display6(googlepageTest.java:50)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- display6 -->
  <testcase classname="TestScripts.googlepageTest" name="display7" time="0.003">
    <skipped/>
  </testcase> <!-- display7 -->
  <testcase classname="TestScripts.googlepageTest" name="display7" time="0.002">
    <skipped/>
  </testcase> <!-- display7 -->
  <testcase classname="TestScripts.googlepageTest" name="display7" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [2] but found [1]">
      <![CDATA[java.lang.AssertionError: expected [2] but found [1]
at TestScripts.googlepageTest.display7(googlepageTest.java:57)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 22 stack frames]]>
    </failure>
  </testcase> <!-- display7 -->
  <testcase classname="TestScripts.googlepageTest" name="openurl" time="4.601"/>
</testsuite> <!-- Test1 -->
